import type { Metadata } from 'next'
import './globals.css'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import Head from 'next/head'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
      <main>
          <Navbar />
          {children}
          <Footer />
      </main>
      </body>
    </html>
  )
}
